services:
    DigipolisGent\Domainator9k\CiTypes\JenkinsBundle\Provider\DataTypeProvider:
        tags:
            - { name: data_type_provider }
    DigipolisGent\Domainator9k\CiTypes\JenkinsBundle\FieldType\JenkinsServerChoiceFieldType:
        autowire: true
        tags:
            - { name: field_type}
    DigipolisGent\Domainator9k\CiTypes\JenkinsBundle\FieldType\JenkinsJobChoiceFieldType:
        autowire: true
        tags:
            - { name: field_type}
    DigipolisGent\Domainator9k\CiTypes\JenkinsBundle\Form\Type\JenkinsJobFormType:
        tags: [form.type]