services:
    digip_deploy.jenkins:
        class: DigipolisGent\Domainator9k\CiTypes\JenkinsBundle\Service\Jenkins
        arguments: ["@digip_deploy.ci_type_builder", "@digip_deploy.ci_settings_service", "%kernel.root_dir%"]

    digip_deploy.ci_processor.jenkins:
        class: DigipolisGent\Domainator9k\CiTypes\JenkinsBundle\Service\JenkinsProcessor
        arguments: ["@digip_deploy.ci_apptype_settings_service", "@digip_deploy.jenkins"]
    DigipolisGent\Domainator9k\CiTypes\JenkinsBundle\Provider\DataTypeProvider:
        tags:
            - { name: data_type_provider }
    DigipolisGent\Domainator9k\CiTypes\JenkinsBundle\FieldType\JenkinsServerChoiceFieldType:
        autowire: true
        tags:
            - { name: field_type}
    DigipolisGent\Domainator9k\CiTypes\JenkinsBundle\FieldType\JenkinsGroovyScriptChoiceFieldType:
        autowire: true
        tags:
            - { name: field_type}