name: 'Jenkins'
slug: jenkins

additional_config:
    templates:
        deploy: 'jenkins_template_robo-generic-parameter-gitref'
        revert: 'jenkins_template_robo-generic'
        sync: 'jenkins_template_robo-generic'
        dump: 'jenkins_template_robo-generic'
        validate: 'jenkins_template_code-analysis'
    groovyscripts:
        deploy: 'job.disable()'
        revert: 'job.disable()'
        sync: 'job.disable()'
        dump: 'job.disable()'
        validate: 'job.disable()'